github_checks:
  annotations: true
coverage:
  precision: 2
  round: down
  range: '75...100'
  status:
    patch:
      default:
        # basic
        target: auto
        threshold: 10%
        if_ci_failed: error #success, failure, error, ignore
        base: auto
        branches:
          - main
    project:
      default:
        only_pulls: true
        target: auto
        threshold: 10%
        branches:
          - main
        flags:
          - LWC
          - Apex
      LWC:
        flags:
          - LWC
      Apex:
        flags:
          - Apex
ignore:
  - 'force-app/main/default/staticresources/**'
component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - main
  individual_components:
    - component_id: module_core # this is an identifier that should not be changed
      name: core # this is a display name, and can be changed freely
      paths:
        - force-app/**
    - component_id: module_unpackaged
      name: unpackaged
      paths:
        - unpackaged/**
