# Unique name for this workflow
name: On Push

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:
    # paths-ignore:
    #   - 'sfdx-project.json'
    #   - 'README.md'
    #   - 'docs/**'
    #   - 'doc-assets/**'
    #   - '.vscode/**'
    #   - '.github/**'
    paths:
      - 'force-app/**'
      - 'config/**'
      - '.github/workflows/ci.yml'

# Jobs to be executed
jobs:
  pmd-analysis:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      # Install PMD
      - name: 'Install PMD'
        id: pmd
        run: |
          PMD_VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | grep '.tag_name' | sed 's:.*/::' | sed 's:",::')
          echo $PMD_VERSION
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-dist-$PMD_VERSION-bin.zip
          unzip pmd-dist-$PMD_VERSION-bin.zip -d ~
          mv ~/pmd-bin-$PMD_VERSION ~/pmd
          ~/pmd/bin/pmd --version

      # Run PMD scan
      - name: 'Run PMD scan'
        id: pmd_sarif
        run: ~/pmd/bin/pmd check --dir force-app --rulesets config/pmd/ruleset.xml --format sarif --cache .pmdCache --minimum-priority "Medium High" --no-progress

      - name: Upload violations file in SARIF format
        if: steps.pmd.outputs.violations != 0
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
          category: PMD analysis

  sfdx-scanner:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - name: Install SFDX CLI and Scanner
        run: |
          npm install @salesforce/cli --global
          sf plugins install @salesforce/sfdx-scanner

      - name: Run SFDX Scanner
        uses: mitchspano/sfdx-scan-pull-request@main
        with:
          pmdconfig: 'config/pmd/ruleset.xml'
          severity-threshold: 4
          report-mode: 'check-runs'
          target: 'force-app'
          engine: 'pmd'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
