name: CodeScan Manual SARIF

# run-name: Repository PMD scan by @${{ github.actor }}

on:
  workflow_dispatch:

env:
  AUTORABIT_CODESCAN_TOKEN: ${{ secrets.AUTORABIT_CODESCAN_TOKEN }}
  AUTORABIT_CODESCAN_ORGANIZATION: ${{ vars.AUTORABIT_CODESCAN_ORG }}
  AUTORABIT_CODESCAN_PROJECT_KEY: ${{ vars.AUTORABIT_CODESCAN_PROJECT_KEY }}
  AUTORABIT_CODESCAN_URI: ${{ vars.AUTORABIT_CODESCAN_URI }}
  AUTORABIT_CODESCAN_EXPORT_FILENAME: 'autorabit_codescan_export.csv'
  STOP_BUILD_ON_QUALITY_GATE: 'true'

jobs:
  codescan-sarif:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    outputs:
      filename: ${{ steps.set_filename.outputs.filename }}

    steps:
      - uses: actions/checkout@v4

      - name: install sfdx
        shell: pwsh
        run: |
          $version_number='2.58.7'
          Write-Output "Installing SFDX CLI"
          npm install -g npm
          node --version
          Write-Output "npm install --global @salesforce/cli@$version_number "
          npm install --global @salesforce/cli@$version_number
      - name: SETUP JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: install CS plugin
        run: |
          echo "Installing AutoRabit Codescanner SFDX Plugin"
          echo y | sfdx plugins:install sfdx-codescan-plugin

      - name: cs export util
        run: |
          # echo "Installing AutoRabit Codescanner Export Utility"
          # npm i codescan-export -g
          # codescan-export -v
      - name: 'Set Filename'
        id: set_filename
        run: echo "filename=${{ github.event.repository.name }}_$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"

      # Run scan
      - name: 'Run scan'
        id: run_scan
        run: |
          # sfdx codescan:run --token ${CODESCAN_TOKEN} --projectkey ${MY_PROJECT_KEY} --organization ${MY_PROJECT_KEY} -Dsonar.analysis.report.type=sarif -Dsonar.analysis.report.enabled=true
          sfdx codescan:run --token ${{secrets.AUTORABIT_CODESCAN_TOKEN}} --projectkey ${{vars.AUTORABIT_CODESCAN_PROJECT_KEY}} --organization ${{vars.AUTORABIT_CODESCAN_ORG}} -Dsonar.analysis.report.type=sarif -Dsonar.analysis.report.enabled=true --server ${{ vars.AUTORABIT_CODESCAN_URI }}
