# This is a main workflow to trigger on push events

name: PMD Scan on Push/PR Open

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  scan-pmd-action:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run PMD
        id: pmd-action
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'config/pmd/ruleset.xml'
          analyzeModifiedFilesOnly: true
          createGitHubAnnotations: true
          uploadSarifReport: false
      - name: Upload violations file in SARIF format
        if: steps.pmd-action.outputs.violations != 0
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
          category: PMD
          wait-for-processing: true
      # Check for PMD violations
      - name: 'Check for PMD violations'
        if: steps.pmd-action.outputs.violations != 0
        run: exit 1
