# Unique name for this workflow
name: On PR (metadata format)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

# Jobs to be executed
jobs:
  run-pmd-metadata-format-copado:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      # Install PMD
      - name: 'Install PMD'
        id: pmd
        run: |
          PMD_VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | grep '.tag_name' | sed 's:.*/::' | sed 's:",::')
          echo $PMD_VERSION
          PMD_VERSION=7.5.0
          wget -q https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-dist-$PMD_VERSION-bin.zip
          unzip -q pmd-dist-$PMD_VERSION-bin.zip -d ~
          mv ~/pmd-bin-$PMD_VERSION ~/pmd
          ~/pmd/bin/pmd --version

      - name: Collect changed files
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: ${{ github.head_ref }}
        run: |
          echo "Files for this PR:"
          gh pr diff "$BRANCH" --name-only > changed.txt
          cat changed.txt

      # Run PMD scan - apex
      # - name: 'Run PMD scan to SARIF - APEX'
      #   id: pmd_sarif
      #   run: ~/pmd/bin/pmd check --dir src/classes --dir src/triggers --rulesets config/pmd/ruleset.xml --format sarif --report-file pmd-cli-report-apex.sarif  --cache .pmdCache --no-progress --no-fail-on-violation --no-fail-on-error --ignore-list config/pmd/ignore.txt --minimum-priority 2

      # - name: Upload violations file in SARIF format
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: pmd-cli-report-apex.sarif
      #     category: PMD_code

      # # Run PMD scan - XML
      # - name: 'Run PMD scan to SARIF - XML'
      #   id: pmd_sarif_xml
      #   run: ~/pmd/bin/pmd check --dir src --rulesets config/pmd/ruleset.xml --format sarif --report-file pmd-cli-report-xml.sarif  --no-cache --no-progress --no-fail-on-violation --no-fail-on-error --ignore-list config/pmd/ignore.txt --minimum-priority 2 --force-language xml

      # - name: Upload violations file in SARIF format
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: pmd-cli-report-xml.sarif
      #     category: PMD_xml

      - name: 'Run PMD scan to CSV - XML'
        id: pmd_csv_metadata
        run: |
          ~/pmd/bin/pmd check --dir src --rulesets config/pmd/ruleset.xml --format csv --report-file pmd-xml.csv --cache .pmdCache --no-progress --no-fail-on-violation --no-fail-on-error --property package=false --property problem=false --property ruleSet=false --ignore-list config/pmd/ignore.txt --minimum-priority 2 --force-language xml --use-version 1.0 --verbose

      - name: Read CSV - XML
        id: csv_metadata
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pmd-xml.csv

      - name: Create MD - XML
        uses: petems/csv-to-md-table-action@master
        id: csv-table-output-xml
        with:
          csvinput: ${{ steps.csv_metadata.outputs.content }}

      - name: Step Table - XML
        id: md_to_output_metadata
        run: |
          echo "${{steps.csv-table-output-xml.outputs.markdown-table}}"
          echo "${{steps.csv-table-output-xml.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
