# This is a main workflow to trigger on pull requests for DX repositories

name: Pull Request Scan (DX)

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]

env:
  blocking_severity: 2
  csv_properties: --property package=false --property problem=false --property ruleSet=false
  hidden_comment_prefix: <!--dtc-scanner-->
  run_sarif: 'true'

jobs:
  scan-pmd:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest

    outputs:
      blockers_text: ${{ steps.csv_blockers.outputs.content }}
      blockers_count: ${{ steps.evaluate_violations_blockers.outputs.blockers_count }}

    steps:
      # Check out the source code
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: 'Set Filename'
        id: set_filename
        run: echo "filename=${{ github.event.repository.name }}_$(date --utc +%Y%m%d_%H%M%SZ)" >> $GITHUB_OUTPUT

      # Install PMD
      - name: Install PMD
        id: pmd
        run: |
          PMD_VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | grep '.tag_name' | sed 's:.*/::' | sed 's:",::')
          echo $PMD_VERSION
          if [ ! -f "./pmd-dist-$PMD_VERSION-bin.zip" ]; then 
            wget -q https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-dist-$PMD_VERSION-bin.zip
            unzip -q pmd-dist-$PMD_VERSION-bin.zip -d ~
            mv ~/pmd-bin-$PMD_VERSION ~/pmd
            ~/pmd/bin/pmd --version
          fi

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          output_renamed_files_as_deleted_and_added: true
          separator: ','
          old_new_separator: '\n'
          old_new_files_separator: '\n'

      - name: Add changed files to changed.txt
        shell: bash
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          IFS=$',' read -a ALL_CHANGED_FILES <<< "${{ steps.changed-files.outputs.all_changed_files }}"
           for file in "${ALL_CHANGED_FILES[@]}"; do
             echo $file >> changed.txt
           done
          cat changed.txt

      ####################### ALL VIOLATIONS CHECK

      - name: Run PMD scan to CSV - All violations
        id: pmd_csv_all
        run: |
          rm -f .pmdCache
          ~/pmd/bin/pmd check --file-list changed.txt --rulesets config/dtc_pmd_ruleset.xml --format csv --report-file ${{ steps.set_filename.outputs.filename }}.csv --no-cache --no-progress --no-fail-on-violation --no-fail-on-error $csv_properties

      - name: Priority to Severity
        id: priority_to_severity_all
        run: sed -i 's|"Priority"|"Severity"|g' ${{ steps.set_filename.outputs.filename }}.csv

      ######## EVALUATE ALL VIOLATIONS

      - name: Evaluate all violations
        id: evaluate_violations_all
        run: |
          csv_line_count=$(wc -l ${{ steps.set_filename.outputs.filename }}.csv|awk '{print $1}')
          #echo $csv_line_count
          violation_count=$((csv_line_count - 1))
          echo "violation_count=$violation_count" >> $GITHUB_OUTPUT
          echo "VIOLATIONS FOUND:" $violation_count  # Print to console
           if [[ $violation_count > 0 ]]; then
             VIOLATION_STRING="$violation_count Scanning Violations Detected (all severities) in changed files - download CSV to check"
             echo "::error::$VIOLATION_STRING"
           elif [[ $violation_count == 0 ]]; then
             echo "::notice::No Scanning Violations Detected"
             exit 0
           fi

      - name: Upload all violations file in CSV format
        if: ${{ steps.evaluate_violations_all.outputs.violation_count > 0 }}
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.set_filename.outputs.filename }}.csv
          name: ${{ steps.set_filename.outputs.filename }}_PMD
          compression-level: 0

      ##################### BLOCKERS CHECK
      - name: Show only Blockers from CSV
        run: |
          echo "blocking_severity " $blocking_severity
          block_sev=$(($blocking_severity))
          echo "block_sev " $block_sev
          head -n 1 ${{ steps.set_filename.outputs.filename }}.csv > pmd-blockers.csv
          awk -v var="$blocking_severity" -F '","'  'BEGIN {OFS=","} { if (($2 <= var))  print }' ${{ steps.set_filename.outputs.filename }}.csv >> pmd-blockers.csv
          cat pmd-blockers.csv

      - name: Read CSV - Blockers
        id: csv_blockers
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pmd-blockers.csv

      - name: Create MD - Blockers
        uses: petems/csv-to-md-table-action@master
        id: csv-table-blockers
        with:
          csvinput: ${{ steps.csv_blockers.outputs.content }}

      # Check blocker count from CSV
      # If has blockers, exit 1
      - name: Evaluate Blocker Violations
        id: evaluate_violations_blockers
        run: |
          csv_blocker_count=$(wc -l pmd-blockers.csv|awk '{print $1}')
          blockers_count=$((csv_blocker_count - 1))
          echo "blockers_count=$blockers_count" >> $GITHUB_OUTPUT
          echo "BLOCKERS FOUND:" $blockers_count  # Print to console
          if [[ $blockers_count > 0 ]]; then
            echo "## Blockers in Changed Files" >> $GITHUB_STEP_SUMMARY
            echo "${{steps.csv-table-blockers.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
            BLOCKER_STRING="$blockers_count Blocking Violations Detected"
            echo "::error::$BLOCKER_STRING"
          elif [[ $blockers_count == 0 ]]; then
            echo "::notice::No Blocking Violations Detected"
          fi

      ############# OTHER VIOLATIONS CHECK

      - name: Show non-Blockers from CSV
        run: |
          echo "blocking_severity " $blocking_severity
          block_sev=$(($blocking_severity))
          echo "block_sev " $block_sev
          #head -n 1 ${{ steps.set_filename.outputs.filename }}.csv > pmd-other.csv
          awk -v var="$blocking_severity" -F '","'  'BEGIN {OFS=","} { if (($2 > var))  print }' ${{ steps.set_filename.outputs.filename }}.csv >> pmd-other.csv
          cat pmd-other.csv

      - name: Priority to Severity
        id: priority_to_severity_other
        run: sed -i 's|"Priority"|"Severity"|g' pmd-other.csv

      - name: Read CSV - other
        id: csv_other
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pmd-other.csv

      - name: Create MD - other
        uses: petems/csv-to-md-table-action@master
        id: csv-table-other
        with:
          csvinput: ${{ steps.csv_other.outputs.content }}

      - name: Evaluate Other Violations
        id: evaluate_violations_other
        run: |
          csv_other_count=$(wc -l pmd-other.csv|awk '{print $1}')
          other_count=$((csv_other_count - 1))
          echo "other_count=$other_count" >> $GITHUB_OUTPUT
          echo "NON-BLOCKER FOUND:" $other_count  # Print to console
          if [[ $other_count > 0 ]]; then
            echo "## Non-Blocking Violations in Changed Files" >> $GITHUB_STEP_SUMMARY
            echo "${{steps.csv-table-other.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
          fi

      # Run PMD SARIF can
      - name: Run PMD scan to SARIF
        id: pmd_sarif
        if: ${{ steps.evaluate_violations_all.outputs.violation_count > 0 }} && $run_sarif == 'true'
        run: |
          ~/pmd/bin/pmd check --file-list changed.txt --rulesets config/dtc_pmd_ruleset.xml --format sarif --report-file pmd-cli-report.sarif --no-cache --no-progress --no-fail-on-violation --no-fail-on-error --minimum-priority 2

      - name: Upload violations file in SARIF format
        if: ${{ steps.evaluate_violations_all.outputs.violation_count > 0 }} && $run_sarif == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-cli-report.sarif
          category: PMD

  write-blockers-comment:
    needs: scan-pmd
    permissions:
      issues: write
      pull-requests: write
    if: ${{ needs.scan-pmd.outputs.blockers_count < 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: Filter blocker columns
        run: |
          printf '${{ needs.scan-pmd.outputs.blockers_text}}' > pmd-blockers-input.csv  
          cut -d "," -f 1,3,4 pmd-blockers-input.csv >> pmd-blocker-comment.csv
          cat pmd-blocker-comment.csv
      - name: Read CSV - other
        id: csv_comment
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pmd-blocker-comment.csv

      - name: Create MD - other
        uses: petems/csv-to-md-table-action@master
        id: csv-comment-md
        with:
          csvinput: ${{ steps.csv_comment.outputs.content }}

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: ${{ env.hidden_comment_prefix }}

      - name: Create comment
        if: steps.find_comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ env.hidden_comment_prefix }}
            ## Blockers
            ${{steps.csv-comment-md.outputs.markdown-table}}
            [View details](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})

      - name: Update comment
        if: ${{ steps.find_comment.outputs.comment-id != '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: 'replace'
          body: |
            ${{ env.hidden_comment_prefix }}
            ## Blockers
            ${{steps.csv-comment-md.outputs.markdown-table}}
            [View details](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})

  call-blockers-comment:
    needs: scan-pmd
    permissions:
      issues: write
      pull-requests: write
    if: ${{ needs.scan-pmd.outputs.blockers_count > 0}}
    uses: ./.github/workflows/rollout-ci_violations_comment_call.yml
    with:
      input_blockers_text: ${{ needs.scan-pmd.outputs.blockers_text }}

  evaluate-exit-code:
    runs-on: ubuntu-latest
    needs: scan-pmd
    steps:
      - name: Check Blocker Count for Exit Code
        if: ${{ needs.scan-pmd.outputs.blockers_count > 0 }}
        run: exit 1
