name: Release Please
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        name: Release Please Action
        with:
          token: ${{ secrets.DEPENDABOT_TOKEN }}
      - name: Echo Release Created
        run: echo "${{ steps.release.outputs.releases_created }}"
      - name: Echo PR Created
        run: echo "${{ steps.release.outputs.prs_created }}"
